### ISSUE TITLE
2021.12.x : 2021-12-13 18:58:31 WARNING (MainThread) [homeassistant.helpers.entity] Entity vacuum.dreame (<class 'custom_components.xiaomi_vacuum.vacuum.MiroboVacuum'>) implements device_state_attributes. Please report it to the custom component author.

### ISSUE THREAD

**Issue by pergolafabio** [microfrost1/xiaomi_vacuum#9]
Hi, i see this error

is it coming from your custom? any idea what needs to be changed?

thnx

**Comment by microfrost1** [comment]
Hi,

Possibly a breaking change from HA 2021.12. I actually moved to Valetudo a few months ago on my Dreame so I don't use this component anymore. I can see a fork by pooyashahidi which looks better in everyway if you are unrooted.

Thanks

**Comment by pergolafabio** [comment]
yes, indeed
but do you mean this fork? thats for the D9 , not F9
https://github.com/pooyashahidi/xiaomi_vacuum

i believe it doesnt work on F9 models

isnt it possible to change your code one last time to fix the breaking change?
my device isnt rooted ...or if you know another component that can be used with non-rooted Dreame F9 ?

**Comment by microfrost1** [comment]
Hi,

I'm 99% sure that the D9 and F9 use the same API, pooyashahidi even comments in the link you posted that the F9 should work. The 1C had a different variant which was short lived by Dreame/Xiaomi but I believe all new models follow the same standard.

It's difficult for me to make a change as I can't easily test it nor do I have much time at the moment. I'm happy to merge a pull request in. I'm not running 2021.12 yet as I tend to wait for the 3rd or 4th release once issues have been ironed out.

Thanks

**Comment by pergolafabio** [comment]
ah ok, np
gonna try it, thnx for feedback :-)

**Comment by pergolafabio** [comment]
ok, confirmed working!! thnx for info
